const STATUS = {
    SUCCESS_CODE: 200,
    CREATED_CODE: 201,
    NON_AUTHORITATIVE_INFORMATION_CODE: 203,
    NO_CONTENT_CODE: 204,
    BAD_REQUEST_CODE: 400,
    UNAUTHORIZED_CODE: 401,
    PAYMENT_REQUIRED_CODE: 402,
    FORBIDDEN_CODE: 403,
    NOT_FOUND_CODE: 404,
    CONFLICT_CODE: 409,
    INTERNAL_SERVER_ERROR_CODE: 500
};

module.exports = {
    STATUS
};